version: '3.3'
services:
  # app:
  #   build: .
  #   depends_on:
  #     - postgres
  #   environment:
  #     DATABASE_URL: postgresql://my_user:my_pwd@localhost:5432/automotive_parts_organizational_system
  #   ports:
  #     - "3000:3000"
  postgres:
    image: postgres:15
    container_name: postgres-database-container
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_pwd
      POSTGRES_DB: automotive_parts_organizational_system
    ports:
      - "5432:5432"
# volumes:
#   postgres_data:
#     driver: local
